version: "3"
services:
  mmplayer:
    image: hclasmn/music
    container_name: mm
    ports:
#      - "9988:8080"
      - "3080:80"
      - "9989:3000"
      - "3100:3000
      - "3100:80
    volumes:
#      - /docker/mmplayer/Vue-mmPlayer-master:/Vue-mmPlayer-master
      - /docker/NeteaseMusic/mmplayer/nginx/dist:/usr/share/nginx/html
      - /docker/NeteaseMusic/mmplayer/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#      - /docker/NeteaseMusic/mmplayer/nginx/conf.d:/etc/nginx/conf.d
#      - /docker/NeteaseMusic/mmplayer/nginx/logs:/var/log/nginx
#    working_dir: /Vue-mmPlayer-master/dist
#    command: python -m SimpleHTTPServer 8080
#    environment:
#      - VUE_APP_BASE_API_URL=https://api.900109.xyz:8443
    depends_on:
      - qq-api
      - mixmusicapi
      - neteasecloud-api